data = [
    ['cap', 'xap', 'uap'],
    ['skp', 'xkp', 'ukp'],
    ['hlm', 'xlm', 'ulm'],
    ['fhl', 'xhl', 'uhl'],
    ['ghm', 'xhm', 'uhm'],
    ['crn', 'xrn', 'urn'],
    ['msk', 'xsk', 'usk'],
    ['bhm', 'xh9', 'uh9'],
    ['qui', 'xui', 'uui'],
    ['lea', 'xea', 'uea'],
    ['hla', 'xla', 'ula'],
    ['stu', 'xtu', 'utu'],
    ['rng', 'xng', 'ung'],
    ['scl', 'xcl', 'ucl'],
    ['chn', 'xhn', 'uhn'],
    ['brs', 'xrs', 'urs'],
    ['spl', 'xpl', 'upl'],
    ['plt', 'xlt', 'ult'],
    ['fld', 'xld', 'uld'],
    ['gth', 'xth', 'uth'],
    ['ful', 'xul', 'uul'],
    ['aar', 'xar', 'uar'],
    ['ltp', 'xtp', 'utp'],
    ['buc', 'xuc', 'uuc'],
    ['sml', 'xml', 'uml'],
    ['lrg', 'xrg', 'urg'],
    ['kit', 'xit', 'uit'],
    ['tow', 'xow', 'uow'],
    ['gts', 'xts', 'uts'],
    ['bsh', 'xsh', 'ush'],
    ['spk', 'xpk', 'upk'],
    ['lgl', 'xlg', 'ulg'],
    ['vgl', 'xvg', 'uvg'],
    ['mgl', 'xmg', 'umg'],
    ['tgl', 'xtg', 'utg'],
    ['hgl', 'xhg', 'uhg'],
    ['lbt', 'xlb', 'ulb'],
    ['vbt', 'xvb', 'uvb'],
    ['mbt', 'xmb', 'umb'],
    ['tbt', 'xtb', 'utb'],
    ['lbl', 'zlb', 'ulc'],
    ['vbl', 'zvb', 'uvc'],
    ['mbl', 'zmb', 'umc'],
    ['tbl', 'ztb', 'utc'],
    ['hbl', 'zhb', 'uhc'],
    ['dr1', 'dr6', 'drb'],
    ['dr2', 'dr7', 'drc'],
    ['dr3', 'dr8', 'drd'],
    ['dr4', 'dr9', 'dre'],
    ['dr5', 'dra', 'drf'],
    ['ba1', 'ba6', 'bab'],
    ['ba2', 'ba7', 'bac'],
    ['ba3', 'ba8', 'bad'],
    ['ba4', 'ba9', 'bae'],
    ['ba5', 'baa', 'baf'],
    ['pa1', 'pa6', 'pab'],
    ['pa2', 'pa7', 'pac'],
    ['pa3', 'pa8', 'pad'],
    ['pa4', 'pa9', 'pae'],
    ['pa5', 'paa', 'paf'],
    ['ne1', 'ne6', 'neb'],
    ['ne2', 'ne7', 'nec'],
    ['ne3', 'ne8', 'ned'],
    ['ne4', 'ne9', 'nee'],
    ['ne5', 'nea', 'nef'],
    ['hax', '9ha', '7ha'],
    ['axe', '9ax', '7ax'],
    ['2ax', '92a', '72a'],
    ['mpi', '9mp', '7mp'],
    ['wax', '9wa', '7wa'],
    ['lax', '9la', '7la'],
    ['bax', '9ba', '7ba'],
    ['btx', '9bt', '7bt'],
    ['gax', '9ga', '7ga'],
    ['gix', '9gi', '7gi'],
    ['clb', '9cl', '7cl'],
    ['spc', '9sp', '7sp'],
    ['mac', '9ma', '7ma'],
    ['mst', '9mt', '7mf'],
    ['fla', '9fl', '7fl'],
    ['whm', '9wh', '7wh'],
    ['mau', '9m9', '7m7'],
    ['gma', '9gm', '7gm'],
    ['ssd', '9ss', '7ss'],
    ['scm', '9sm', '7sm'],
    ['sbr', '9sb', '7sb'],
    ['flc', '9fc', '7fc'],
    ['crs', '9cr', '7cr'],
    ['bsd', '9bs', '7bs'],
    ['lsd', '9ls', '7ls'],
    ['wsd', '9wd', '7wd'],
    ['2hs', '92h', '72h'],
    ['clm', '9cm', '7cm'],
    ['gis', '9gs', '7gs'],
    ['bsw', '9b9', '7b7'],
    ['flb', '9fb', '7fb'],
    ['gsd', '9gd', '7gd'],
    ['dgr', '9dg', '7dg'],
    ['dir', '9di', '7di'],
    ['kri', '9kr', '7kr'],
    ['bld', '9bl', '7bl'],
    ['tkf', '9tk', '7tk'],
    ['tax', '9ta', '7ta'],
    ['bkf', '9bk', '7bk'],
    ['bal', '9b8', '7b8'],
    ['jav', '9ja', '7ja'],
    ['pil', '9pi', '7pi'],
    ['ssp', '9s9', '7s7'],
    ['glv', '9gl', '7gl'],
    ['tsp', '9ts', '7ts'],
    ['spr', '9sr', '7sr'],
    ['tri', '9tr', '7tr'],
    ['brn', '9br', '7br'],
    ['spt', '9st', '7st'],
    ['pik', '9p9', '7p7'],
    ['bar', '9b7', '7o7'],
    ['vou', '9vo', '7vo'],
    ['scy', '9s8', '7s8'],
    ['pax', '9pa', '7pa'],
    ['hal', '9h9', '7h7'],
    ['wsc', '9wc', '7wc'],
    ['sbw', '8sb', '6sb'],
    ['hbw', '8hb', '6hb'],
    ['lbw', '8lb', '6lb'],
    ['cbw', '8cb', '6cb'],
    ['sbb', '8s8', '6s7'],
    ['lbb', '8l8', '6l7'],
    ['swb', '8sw', '6sw'],
    ['lwb', '8lw', '6lw'],
    ['lxb', '8lx', '6lx'],
    ['mxb', '8mx', '6mx'],
    ['hxb', '8hx', '6hx'],
    ['rxb', '8rx', '6rx'],
    ['sst', '8ss', '6ss'],
    ['lst', '8ls', '6ls'],
    ['gst', '8cs', '6cs'],
    ['bst', '8bs', '6bs'],
    ['wst', '8ws', '6ws'],
    ['wnd', '9wn', '7wn'],
    ['ywn', '9yw', '7yw'],
    ['bwn', '9bw', '7bw'],
    ['gwn', '9gw', '7gw'],
    ['scp', '9sc', '7sc'],
    ['gsc', '9qs', '7qs'],
    ['wsp', '9ws', '7ws'],
    ['ktr', '9ar', '7ar'],
    ['wrb', '9wb', '7wb'],
    ['axf', '9xf', '7xf'],
    ['ces', '9cs', '7cs'],
    ['clw', '9lw', '7lw'],
    ['btl', '9hw', '7hw'],
    ['skr', '9qr', '7qr'],
    ['ob1', 'ob6', 'obb'],
    ['ob2', 'ob7', 'obc'],
    ['ob3', 'ob8', 'obd'],
    ['ob4', 'ob9', 'obe'],
    ['ob5', 'oba', 'obf'],
    ['am1', 'am6', 'amb'],
    ['am2', 'am7', 'amc'],
    ['am3', 'am8', 'amd'],
    ['am4', 'am9', 'ame'],
    ['am5', 'ama', 'amf'],
]
def create_code_mapping(data):
    code_mapping = {}
    for entry in data:
        for code in entry:
            code_mapping[code] = entry[0]
    return code_mapping
notfound = [
    ['ch1',  'Small Charm'],
    ['ch2', 'Large Charm'],
    ['ch3', 'Grand Charm'],
]
def create_notfound_mapping(notfound_data):
    notfound_map = {}
    for code, item_name in notfound_data:
        notfound_map[item_name.lower()] = code
    return notfound_map
notfound_map = create_notfound_mapping(notfound)

regular_colors = {
    '1752220': 'Red',
    '1146986': 'Blue',
    '3066993': 'Green',
    '2067276': 'Yellow',
    '3447003': 'Orange',
    '2123412': 'Purple',
    '10181046': 'Cyan',
    '7419530': 'Magenta',
    '15277667': 'Lime',
    '11342935': 'Pink',
    '15844367': 'Teal',
    '12745742': 'Lavender',
    '15105570': 'Brown',
    '11027200': 'Beige',
    '15158332': 'Maroon',
    '10038562': 'Mint',
    '9807270': 'Olive',
    '9936031': 'Apricot',
    '8359053': 'Navy',
    '12370112': 'Grey',
    '3426654': 'White',
    '2899536': 'Black',
    '16776960': 'Dark Green'
}
